---
datatype: aws.rds.db_cluster_parameter
metadata:
  profile: default
  region: ap-northeast-1
  resourceid: default.mysql8.0.replication_optimize_for_static_plugin_config
specifics:
  AllowedValues: 0,1
  ApplyMethod: pending-reboot
  ApplyType: dynamic
  DataType: boolean
  Description: If enabled, use shared locks, and avoid unnecessary lock acquisitions,
    to improve performance for semisynchronous replication
  IsModifiable: true
  MinimumEngineVersion: 8.0.23
  ParameterName: replication_optimize_for_static_plugin_config
  ParameterValue: '0'
  Source: engine-default
  SupportedEngineModes:
  - provisioned
...

