---
datatype: aws.iam.policies
metadata:
  profile: default
  region: __SINGLE_REGION
  resourceid: ApplicationDiscoveryServiceContinuousExportServiceRolePolicy
  single_region: true
specifics:
  Arn: arn:aws:iam::aws:policy/aws-service-role/ApplicationDiscoveryServiceContinuousExportServiceRolePolicy
  AttachmentCount: 0
  CreateDate: 2018-08-09 20:22:01+00:00
  DefaultVersionId: v2
  IsAttachable: true
  Path: /aws-service-role/
  PermissionsBoundaryUsageCount: 0
  PolicyId: ANPAJMGMY3P6OEWOELRFE
  PolicyName: ApplicationDiscoveryServiceContinuousExportServiceRolePolicy
  UpdateDate: 2018-08-13 22:31:21+00:00
...

