---
datatype: aws.iam.policies
metadata:
  profile: default
  region: __SINGLE_REGION
  resourceid: AWSApplicationMigrationEC2Access
  single_region: true
specifics:
  Arn: arn:aws:iam::aws:policy/AWSApplicationMigrationEC2Access
  AttachmentCount: 0
  CreateDate: 2021-04-07 07:05:22+00:00
  DefaultVersionId: v10
  IsAttachable: true
  Path: /
  PermissionsBoundaryUsageCount: 0
  PolicyId: ANPAZKAPJZG4OBKWG2D2O
  PolicyName: AWSApplicationMigrationEC2Access
  UpdateDate: 2026-02-12 18:00:41+00:00
...

