---
datatype: aws.iam.policies
metadata:
  profile: default
  region: __SINGLE_REGION
  resourceid: AWSApplicationAutoscalingKafkaClusterPolicy
  single_region: true
specifics:
  Arn: arn:aws:iam::aws:policy/aws-service-role/AWSApplicationAutoscalingKafkaClusterPolicy
  AttachmentCount: 0
  CreateDate: 2020-08-24 18:36:01+00:00
  DefaultVersionId: v1
  IsAttachable: true
  Path: /aws-service-role/
  PermissionsBoundaryUsageCount: 0
  PolicyId: ANPAZKAPJZG4FTCIZBJA2
  PolicyName: AWSApplicationAutoscalingKafkaClusterPolicy
  UpdateDate: 2020-08-24 18:36:01+00:00
...

